### ISSUE TITLE
Support kitties puking glitter

### ISSUE THREAD

**Issue by ellamental** [MilitantMom/MoonBot#2]
Kitties puking glitter is objectively obnoxiously cute and all apps should support it.

**Comment by ellamental** [comment]
@MilitantMom can we make this a priority?

**Comment by MilitantMom** [comment]
I support it, we can def make this a priority. How do we go about it?

**Comment by ellamental** [comment]
Good question... can we make it an emoji?

**Comment by MilitantMom** [comment]
Yes im open to it! The Discord Development Portal Bot page natively supports up to 2,000 emoji's do you have an example of which one you would like me to add? Also where do you think it would be best used?
